version: '3.8'
services:
  rtmp_server:
    build: .
    container_name: rtmp_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
      - 8080:8080
    networks:
      - rtmp_server_network
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0'
          memory: 256MB
networks:
  rtmp_server_network:
    driver: bridge